# Generated by Django 2.0 on 2021-03-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('idAnimal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_animal', models.CharField(choices=[('CERDO', 'CERDO')], default='', max_length=100)),
                ('peso_animal', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoteAnimal',
            fields=[
                ('idLoteAnimal', models.AutoField(primary_key=True, serialize=False)),
                ('peso_lote', models.FloatField()),
                ('precio_costo', models.FloatField()),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('peso_producto', models.FloatField()),
                ('precio_costo', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('utilidad_producto', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rendimiento',
            fields=[
                ('idRendimiento', models.AutoField(primary_key=True, serialize=False)),
                ('total_costo', models.FloatField()),
                ('total_venta', models.FloatField()),
                ('margen_utilidad', models.FloatField()),
                ('rendimiento_neto', models.FloatField()),
                ('merma_deshidratacion', models.FloatField()),
                ('porcentaje_peso_neto', models.FloatField()),
                ('porcentaje_peso_producto', models.FloatField()),
                ('total_costo_producto', models.FloatField()),
                ('total_venta_producto', models.FloatField()),
                ('margen_utilidad_producto', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
