# Generated by Django 3.1.7 on 2021-03-23 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteAnimal',
            fields=[
                ('idLoteAnimal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_lote', models.CharField(default='', max_length=50)),
                ('peso_lote', models.FloatField(default=0)),
                ('precio_costo', models.FloatField(default=0)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rendimiento',
            fields=[
                ('idRendimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rendimiento', models.CharField(default='', max_length=50)),
                ('total_costo', models.FloatField(default=0)),
                ('total_venta', models.FloatField(default=0)),
                ('margen_utilidad', models.FloatField(default=0)),
                ('rendimiento_neto', models.FloatField(default=0)),
                ('merma_deshidratacion', models.FloatField(default=0)),
                ('porcentaje_peso_neto', models.FloatField(default=0)),
                ('porcent_merma_deshidratacion', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('lote', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appAnimalPerformance.loteanimal')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('peso_producto', models.FloatField(default=0)),
                ('precio_costo', models.FloatField(default=0)),
                ('precio_venta', models.FloatField(default=0)),
                ('utilidad_producto', models.FloatField(blank=True, default=0)),
                ('porcentaje_peso_producto', models.FloatField(blank=True, default=0)),
                ('total_costo_producto', models.FloatField(blank=True, default=0)),
                ('total_venta_producto', models.FloatField(blank=True, default=0)),
                ('utilidad_producto_xKG', models.FloatField(blank=True, default=0)),
                ('unidad', models.CharField(choices=[('KG', 'KG'), ('UNIDAD', 'UNIDAD')], default='KG', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('rendimiento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appAnimalPerformance.rendimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('idAnimal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_animal', models.CharField(choices=[('CERDO', 'CERDO')], default='', max_length=100)),
                ('peso_animal', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('lote', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appAnimalPerformance.loteanimal')),
            ],
        ),
    ]
