# Generated by Django 2.0 on 2021-03-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='idLoteAnimal',
        ),
        migrations.RemoveField(
            model_name='loteanimal',
            name='nombre_animal',
        ),
        migrations.RemoveField(
            model_name='rendimiento',
            name='idLoteAnimal',
        ),
        migrations.RemoveField(
            model_name='rendimiento',
            name='nombre_proveedor',
        ),
        migrations.AddField(
            model_name='animal',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='nombre_animal',
            field=models.CharField(choices=[('CERDO', 'CERDO')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='loteanimal',
            name='nombre_proveedor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='loteanimal',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
