# Generated by Django 2.0 on 2021-03-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nombre_animal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso_animal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loteanimal',
            name='peso_lote',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loteanimal',
            name='precio_costo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_producto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='utilidad_producto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='margen_utilidad',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='margen_utilidad_producto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='merma_deshidratacion',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='porcentaje_peso_neto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='porcentaje_peso_producto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='rendimiento_neto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='total_costo',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='total_costo_producto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='total_venta',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='total_venta_producto',
            field=models.FloatField(default=0, null=True),
        ),
    ]
