# Generated by Django 3.1.7 on 2021-03-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0002_animal_loteanimal_producto_rendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(null=True),
        ),
    ]
