# Generated by Django 2.0 on 2021-03-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0002_auto_20210310_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nombre_animal',
            field=models.CharField(choices=[('CERDO', 'CERDO')], default='', max_length=100),
        ),
    ]
