# Generated by Django 2.0 on 2021-03-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0003_auto_20210311_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='peso_animal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(),
        ),
    ]
