# Generated by Django 2.0 on 2021-02-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0003_auto_20210228_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='nombreAnimal',
            new_name='nombre_animal',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProducto',
            new_name='nombre_producto',
        ),
        migrations.RenameField(
            model_name='rendimiento',
            old_name='nombreProveedor',
            new_name='nombre_proveedor',
        ),
    ]
