# Generated by Django 3.1.7 on 2021-03-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0003_auto_20210319_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='lote',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appAnimalPerformance.loteanimal'),
        ),
        migrations.AddField(
            model_name='loteanimal',
            name='nombre_lote',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='animal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appAnimalPerformance.animal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='rendimiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appAnimalPerformance.rendimiento'),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='lote',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appAnimalPerformance.loteanimal'),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='nombre_rendimiento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso_animal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loteanimal',
            name='peso_lote',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loteanimal',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_producto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_peso_producto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='total_costo_producto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='total_venta_producto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='utilidad_producto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='utilidad_producto_xKG',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='margen_utilidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='merma_deshidratacion',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='porcentaje_peso_neto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='rendimiento_neto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='total_costo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='total_venta',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
    ]
