# Generated by Django 3.1.7 on 2021-03-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0004_auto_20210320_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteanimal',
            name='peso_lote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loteanimal',
            name='precio_costo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
