# Generated by Django 2.0 on 2021-03-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0004_auto_20210311_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('KG', 'KG'), ('UNIDAD', 'UNIDAD')], default='KG', max_length=10),
        ),
    ]
