# Generated by Django 3.1.7 on 2021-03-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0005_auto_20210320_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='animal',
        ),
    ]
