# Generated by Django 3.1.7 on 2021-03-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0006_auto_20210313_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
