# Generated by Django 3.1.7 on 2021-03-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0008_auto_20210320_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='peso_animal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loteanimal',
            name='peso_lote',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loteanimal',
            name='precio_costo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_peso_producto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='total_costo_producto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='total_venta_producto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='utilidad_producto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='utilidad_producto_xKG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='margen_utilidad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='merma_deshidratacion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='porcentaje_peso_neto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='rendimiento_neto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='total_costo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='total_venta',
            field=models.FloatField(default=0),
        ),
    ]
