# Generated by Django 3.1.7 on 2021-03-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAnimalPerformance', '0009_auto_20210320_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso_producto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(default=0),
        ),
    ]
